from odoo import api, fields, models


class SaleOrderLine(models.Model):
    _inherit = 'sale.order.line'

    matriz_id = fields.Many2one('ventas.matriz',string='Matriz')
    metodologia_id = fields.Many2one('ventas.metodologia', string='Metodología')

    # Campos extras
    grupo_id = fields.Many2one('ventas.grupo', string='Grupo')
    muestra_id = fields.Many2one('product.product', string='Muestra', domain="[('es_muestra', '=', True)]")
    # cantidad_muestra = fields.Integer(string='Cantidad Muestra')
    # presentacion_muestra = fields.Char(string='Presentación')
    # reactivos = fields.Html(string='Reactivos')
    # estandard = fields.Char(string='Estandard')
    # referencia = fields.Char(string='Referencia')
    # observacion = fields.Char(string='Observación')
    # motivo = fields.Char(string='Motivo')

    # Filtros dinamicos
    productos_filtrados = fields.Many2many('product.template', string='Productos filtrados', compute='_compute_productos_filtrados')

    price_subtotal_with_tax = fields.Float(
        string='Subtotal con IVA',
        compute='_compute_price_subtotal_with_tax',
        store=True,
        readonly=True,
    )

    @api.depends('price_unit', 'product_uom_qty')
    def _compute_price_subtotal_with_tax(self):
        for line in self:
            line.price_subtotal_with_tax = line.price_unit * line.product_uom_qty

    def _compute_productos_filtrados(self):
        """
        Método para filtrar los productos:
        1 - Si la compañia es sumi, no se hace nada
        2 - Si la compañia es analitica, se filtra por metodologia y si esta seleccionado el campo acreditado
        """
        for record in self:
            if record.order_id.mostrar_campos_extras == False:
                record.productos_filtrados = False
            else:
                # Filtrar por metodologia
                domain = [('metodologia_ids', 'in', record.metodologia_id.id)]
                if record.order_id.acreditado:
                    domain.append(('acreditado', '=', True))

                # buscamos los productos y guardamos en el campo
                productos = self.env['product.template'].search(domain)
                record.productos_filtrados = productos.ids

    # Cuando se cambia una muestra
    @api.onchange('muestra_id')
    def _onchange_muestra_id(self):
        """
        Se rellenan los campos desde la muestra seleccionada
        """
        if self.muestra_id:
            # Obtenemos el product template
            self.referencia = self.muestra_id.referencia_bibliografica
            
    @api.model
    def _action_launch_stock_rule(self, previous_product_uom_qty=False):
        """
        Launch procurement group run method with required/custom fields genrated by a
        sale order line. This method is intended to be extended in order to add custom
        fields that should be passed to the procurement order generated by a sale order
        line, and then to the related stock moves.
        """
        res = super(SaleOrderLine, self)._action_launch_stock_rule(previous_product_uom_qty)
        for move in self.move_ids:
            move.motivo_id = move.picking_id.sale_id.motivo_id
        return res
